In [1]:
import numpy
numpy.__version__

'1.16.4'

In [2]:
import numpy as np

In [3]:
np?

In [4]:
result = 0
for i in range (100):
    result += i

In [5]:
x = 4
x = "four"

In [6]:
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [7]:
type(L[0])

int

In [23]:
L2 = [str for c in L]
L2

[str, str, str, str, str, str, str, str, str, str]

In [20]:
type(L2[1])

type

In [21]:
L3 = [True, "2", 3.0, 4]
[type(item) for item in L3]

[bool, str, float, int]

In [24]:
import array 
L = list(range(10))
A = array.array('i', L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
import numpy as np
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [28]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [30]:
np.array([1, 2, 3, 4], dtype = 'float32')

array([1., 2., 3., 4.], dtype=float32)

In [41]:
np.array([range(i, i+3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

## Создание массивов с нуля

In [37]:
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [42]:
np.ones((3,5), dtype = float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [43]:
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [44]:
np.arange (0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [46]:
np.arange?

In [47]:
np.linspace?

In [48]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [55]:
np.random.random((3,3))

array([[0.99283353, 0.80063239, 0.18082175],
       [0.87262538, 0.24234532, 0.35916432],
       [0.16905344, 0.10942818, 0.58662829]])

In [56]:
# Создаем массив размером 3 x 3 нормально распределенных
# случайных значения с медианой 0 и стандартным отклонением 1
np.random.normal(0, 1, (3, 3))

array([[-0.17286888, -1.4139051 ,  1.91721608],
       [ 0.52717812,  0.74628108,  0.38273892],
       [ 0.55661663,  0.09953976,  0.22362809]])

In [58]:
# случайные в промежутке от 0-10
np.random.randint(0, 10, (3, 3))

array([[0, 6, 1],
       [5, 1, 6],
       [1, 7, 4]])

In [60]:
# единичная матрица
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [61]:
np.empty(3)

array([1., 1., 1.])

## Массивы библиотеки Numpy 

In [4]:
import numpy as np
np.random.seed(0)

x1 = np.random.randint(10, size = 6)
x2 = np.random.randint(10, size (3, 4))
x3 = np.random.randint(10, size(3, 4, 5))

print("x3 ndim:", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size:", x3.size)

NameError: name 'size' is not defined

In [2]:
x1 = np.random.randint(10, size = 6)
x2 = np.random.randint(10, size (3, 4))
x3 = np.random.randint(10, size(3, 4, 5))

print("x3 ndim:", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size:", x3.size)

NameError: name 'size' is not defined

In [3]:
print("x3 ndim:", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size:", x3.size)

NameError: name 'x3' is not defined